### ISSUE TITLE
Empty keys on Ubuntu 12.04 Firefox 31

### ISSUE THREAD

**Issue by ilya-fiveisky** [zenprotocol/offline-wallet-generator#1]
On offline Ubuntu 12.04 computer and Firefox 31 index.html generates empty keys.
See attached screenshot.

![screenshot from 2017-12-01 22_08_59](https://user-images.githubusercontent.com/4052190/33509850-098fae00-d6e4-11e7-8126-3680cf7048e6.png)

**Comment by somdoron** [comment]
did you run `npm run build` first?

also can you open developer tools and show the error?

**Comment by ilya-fiveisky** [comment]
> did you run npm run build first?

It is from crowdsale application.

> also can you open developer tools and show the error?
```

SyntaxError: let is a reserved identifier main.js:14239
The character encoding of the HTML document was not declared. The document will render with garbled text in some browser configurations if the document contains characters from outside the US-ASCII range. The character encoding of the page must be declared in the document or in the transfer protocol. index.html

```

**Comment by ilya-fiveisky** [comment]
Well, in fact this script will not work at least for any browser version that does not support ECMAScript 2015 because it contains object initializers which were added in this version.
Natural question arises:
**Did you test it at all?** (Except in your newest browser.)
I mean - this wallet generator is intended for offline computers among which there are many old enough ones. And if someone uses offline generator (instead of online) then he uses it for not too small amount of money so such application should be well tested.

**Comment by somdoron** [comment]
@ilya-fiveisky of course we tested it. But yes you are right it is only running on new browsers which support const keyword.

Because we are using webpack it will be easy to add babel-loader and support older versions of javascript, will you be interested in that?

Officially we are not supporting browsers which are past end of life.

**Comment by ilya-fiveisky** [comment]
If you say that it will be easy to support older versions then it would be nice if you do it. And yes I am interested in that because my offline computer is old and I do not want to buy new one or install new OS on it transferring my offline wallets back and forth.

**Comment by ilya-fiveisky** [comment]
I´ve solved the problem for myself. So if nobody needs offline generator for older computers I close the issue.

**Comment by somdoron** [comment]
thanks, feel free to send us a pull request
